image: monitor:5000/buildproject:1

stages:
 - build
 - QA
 - deploy

before_script:
  - chmod +x gradlew

build-jar:
  stage: build
  only:
    - main
  except:
    changes:
      - documents/**/*
  script:
    - curl https://repo.maven.apache.org/maven2/io/vertx/vertx-web-openapi/4.1.3/vertx-web-openapi-4.1.3.pom #hack to fix SSL issues still needed?
    - ./gradlew shadowJar
  artifacts:
    paths:
      - build/libs/

sonarqube:
  stage: QA
  except:
    changes:
      - documents/**/*
  script:
    - curl https://repo.maven.apache.org/maven2/io/vertx/vertx-web-openapi/4.1.3/vertx-web-openapi-4.1.3.pom #hack to fix SSL issues
    - mkdir -p ../documentation/api-spec
    - wget http://project-ii.ti.howest.be/monitor/apis/group-${CI_PROJECT_NAMESPACE:(-2)} -O ../documentation/api-spec/openapi-mars.yaml
    - ./gradlew test sonarqube -Dsonar.host.url=http://sonarqube.ti.howest.be/ -d
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

deploy:
  image: monitor:5000/deployproject:2
  before_script:
    - echo "we don't need gradle or maven anymore, nice!"
  stage: deploy
  only:
    - main
  except:
    changes:
      - documents/**/*
  script:
    - cd build/libs/
    - rename 's/.*\.jar$/mars.jar/' *.jar
    - eval $(ssh-agent -s)
    - echo ${SSH_PRIVATE_KEY:0:5}
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 172.18.18.200 >> ~/.ssh/known_hosts
    - scp -q mars.jar gitlab-runner@172.18.18.200:"/opt/group-${CI_PROJECT_NAMESPACE:(-2)}/mars.jar"
    - echo "New version from CI on $(date)" > mars.txt
    - scp -q mars.txt gitlab-runner@172.18.18.200:"/opt/group-${CI_PROJECT_NAMESPACE:(-2)}/mars.txt"
    - sleep 10
  environment: production
